---
title: "test"
output: html_document
---


#Test 1

```{r first_plot, echo = FALSE}
library(ggplot2)
library(sqldf)
library(scales)

min_time = as.POSIXct(1520515827838/1000, origin="1970-01-01", tz = "")
max_time = as.POSIXct(1520583336015/1000, origin="1970-01-01", tz = "")

files = list.files(path="../data/test/times/", pattern="*.csv", full.names=T, recursive=FALSE)
activities = read.table("../data/test/activities.csv", header = F)
colnames(activities) = c("start", "end", "label")
activities$start = as.POSIXct(activities$start/1000, origin="1970-01-01", tz = "")

i=1
p = ggplot()

for(file in files){
  data = read.table(file, header = F)
  colnames(data) = c("time")
  data$time = as.POSIXct(data$time/1000, origin="1970-01-01", tz = "")
  
  q = paste("SELECT data.time,",toString(i))
  q = paste(q, "as value, activities.label FROM data, activities WHERE data.time >= activities.start AND data.time <= activities.end")
  
  df = sqldf(q)

  p = p + geom_point(data = df, aes(x = time, y = value, colour = label), shape=16, size=3)
  i = i+1
}

break.vec<-c(min_time,
             seq(from=min_time, to=max_time, by="2 hours"),
             p$coordinates$limits[1])

p = p + scale_x_datetime(breaks = break.vec, labels = date_format("%e-%m %H:%M")) + theme(axis.text.x = element_text(angle = 30, hjust = 1))
p
```



```{r}
```

```{r}
```

```{r}
```

